Copyright (c) 2025 김장오 행정사 사무소

All Rights Reserved

이 소프트웨어와 관련 문서 파일(이하 "소프트웨어")의 저작권은 김장오 행정사 사무소에 있습니다.

본 소프트웨어는 저작권자의 명시적인 서면 허가 없이는 복사, 수정, 배포, 또는 
상업적 사용이 금지됩니다.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

---

문의: info@kimjangoh.com
